language: php

dist: trusty
sudo: false

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: nightly

    allow_failures:
      - php: nightly

    fast_finish: true

before_script:
  - composer update

script: vendor/bin/phpunit
